Gusto-API/api.gusto.dev

- swagger-spec/addresses/definition.yaml
- swagger-spec/compensations/definition.yaml
- swagger-spec/employees/definition.yaml
- swagger-spec/employees/detail.yaml
- swagger-spec/employees/list.yaml
- swagger-spec/garnishments/definition.yaml
- swagger-spec/jobs/definition.yaml
- swagger-spec/paid_time_off/definition.yaml
- swagger-spec/swagger.yaml
- swagger-spec/terminations/definition.yaml
Adds the documentation and necessary definitions for the employee list and detail endpoints.
> Add documentation and related definitions for employee endpoint

- reference/Gusto-API.v1.yaml
> Correct SSN value in example

- reference/Gusto-API.v1.yaml
Create a contractor payment
View a contractor payment
Cancel a contractor payment
> Add contractor payment documentation

- reference/Gusto-API.v1.yaml
> Pay Schedule autopilot documentation

- reference/Gusto-API.v1.yaml
> Create documentation for partner managed company

- reference/Gusto-API.v1.yaml
> [GWS] Cancel Payroll docs

- reference/Gusto-API.v1.yaml
I used stoplight studio to add it...  the preview looked alright, but, I'm not sure how much information needs to be there for this (or have enough background on it to write much more than I have).
So, if this needs tweaks, please let me know!
Thanks!
(This also implements ADD-54)
> Adds payroll_reversals endpoint to the docs.

- reference/Gusto-API.v1.yaml
> Remove extraneous arguments from parnter_managed_companies

- reference/Gusto-API.v1.yaml
> Add description about bank account verification flow

- reference/Gusto-API.v1.yaml
> Create documentation for creating a new single pay schedule

- reference/Gusto-API.v1.yaml
A lot of field description are coming out from wikipedia. Let me know if we need to adjust the wordings. 
I also marked a few fields that `does not apply to rev_2020_w4 form`.
> Add employee federal tax documentation

- docs/guides/Embedded Payroll Onboarding.md
removed duplicate 'Forms' section and added disclaimer to end of guide "When building in Gusto's demo environment, companies must be manually approved by Gusto's Developer Relations team."
> Bvu patch 12 9 21

- docs/basics/what's new.md
- docs/guides/Embedded Payroll Onboarding.md
Updated link to update employee's federal taxes on What's New page. Old link was broken.
> Bvu patch 12 14 21

- docs/basics/what's new.md
- docs/guides/Embedded Payroll Onboarding.md
- docs/guides/Updating Payrolls.md
Updated guide to address updating hourly_compensations for salaried employees.
> Bvu patch 12 16 21

- docs/guides/Process Contractor Payments.md
- docs/guides/Process Off-Cycle Payroll.md
- docs/guides/Process Regular Payroll.md
- toc.json
Brokeout payrolls guides and updated TOC
> Brian vu breakout guides

- docs/integration options/Gusto Embedded Payroll.md
> Update Gusto Embedded Payroll.md

- docs/guides/Embedded Payroll Onboarding.md
Moved video tutorial to the top from the bottom.
> Modified docs/guides/Embedded Payroll Onboarding.md

- docs/guides/Building Embedded Payroll.md
Clarifying introduction and how to get a demo company and/or do company onboarding 1st
> Update Building Embedded Payroll.md

- docs/guides/Building Embedded Payroll.md
- docs/guides/Process Regular Payroll.md
- docs/guides/Updating Payrolls.md
Add payroll loom to Building Embedded Payroll, Updating Payroll, and Process Regular Payroll guides.
> Modified 3 files

- reference/Gusto-API.v1.yaml
This reverts commit 75d1021288486f3937f2986f016dce933caf19e8.
> Revert "Brian vu remove beta tags (#137)"

- reference/Gusto-API.v1.yaml
Add verification type, plaid status and last cached balance onto v1 bank account endpoint
> Plaid response

- reference/Gusto-API.v1.yaml
See JIRA ticket: https://jira.gustocorp.com/browse/GWS-3
Related to Zenpayroll PR's:
- https://github.com/Gusto/zenpayroll/pull/120776
- https://github.com/Gusto/zenpayroll/pull/121442
> Add API documentation for /v1/employees/{uuid}/onboarding_status

- reference/Gusto-API.v1.yaml
Documents the changes in this PR: https://github.com/Gusto/zenpayroll/pull/121849
After this is merged, we should add this to the Embedded Payroll Guide.
> Modify Employee onboarding_status endpoint to include enum values

- docs/guides/Embedded Payroll Onboarding.md
- reference/Gusto-API.v1.yaml
JIRA: https://jira.gustocorp.com/browse/GWS-14
Related to changes in https://github.com/Gusto/zenpayroll/pull/123006
> [GWS-14] Modify docs to include direct_deposit_setup
